protocol = "brooks-mfc-gf"
doc = ""
traits = ["has-limits", "has-position", "uses-uart", "uses-serial", "is-daemon"]

[links]
source = "https://github.com/yaq-project/yaqd-brooks"
bugtracker = "https://github.com/yaq-project/yaqd-brooks/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-brooks"

[config]

[config.address]
doc = "brooks-mfc-address within RS-485 network"
type = "int"


[config.stop_bits]
type = {"type"="enum", "name"="stop_bits", "symbols"=["one", "one_and_half", "two"]}
doc = "Number of stop bits."
default = "one"

[config.parity]
type = {"type"="enum", "name"="parity", "symbols"=["O"]}
doc = "Modbus parity."
default = "O"

[config.tag]
type = "string"
doc = "Unique address in the HART protocol network."
default = "none"

[messages]

[messages.get_rate]
doc = "Get current flow rate, in units specified within the config"
response = "double"

[messages.set_rate]
doc = "Set current flow rate, in units specified within the config"
request = [{"name"="rate", "type"="double"}]

[fields]

[fields.rate]
type = "double"
getter = "get_rate"
setter = "set_rate"
kind = "normal"
